### ISSUE TITLE
Add support for dispatching events with PresignedUrl POST completion

### ISSUE THREAD

**Issue by randonia** [jamhall/s3rver#529]
I noticed that `s3rver` won't emit an S3 event upon completion of a POST from a Presigned Url.

The relevant code to trigger an event appear to be missing from [lib/controllers/object.js#L267](https://github.com/jamhall/s3rver/blob/master/lib/controllers/object.js#L267).

Does it make sense for this to emit an event such as `s3:ObjectCreated:Post`? I've gotten a slightly functional sample locally, but it isn't PR worthy just yet. I just verified that uploading a file via POST to a Presigned Url on S3 does indeed trigger an event `s3:ObjectCreated:Post`, which triggered my lambda with the config:
```yaml
    events:
      - s3:
          bucket: my-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .mp4
          existing: true
```

PS: Thanks for your package, it's been fantastic to use!

Original issue here: ar90n/serverless-s3-local/issues/76
